### ISSUE TITLE
How data augmentation is applied to tabular data?

### ISSUE THREAD

**Issue by hellowangqian** [releaunifreiburg/WellTunedSimpleNets#2]
Hi author, thanks for sharing the code. I'm wondering how data augmentation strategies like mix-up, cut-out, cut-mix, etc., can be applied to tabular data (I understand they are usually applied to images though). Please advise, many thanks.

**Comment by perschi** [comment]
When digging through the code, I found that the authors refer to [CutOut](https://github.com/automl/Auto-PyTorch/blob/regularization_cocktails/autoPyTorch/pipeline/components/training/trainer/RowCutOutTrainer.py) and
[CutMix](https://github.com/automl/Auto-PyTorch/blob/regularization_cocktails/autoPyTorch/pipeline/components/training/trainer/RowCutMixTrainer.py). In these two files, you can see that they replace random columns with zero or replace them with values from a random other sample in the batch.

**Comment by ArlindKadra** [comment]
as @perschi nicely mentioned, you could additionally find MixUp [here](https://github.com/automl/Auto-PyTorch/blob/regularization_cocktails/autoPyTorch/pipeline/components/training/trainer/MixUpTrainer.py). Basically, since we are not using an image anymore and there is no information related to neighboring features, we select features randomly.

Let me know if there is something else that is unclear :).
